generate wallet
pungtas/tyron.js pull request #11
Opened 2022-06-13 07:19 UTC by DevPH-Wistkey

@tralkan

2022-06-14 00:12 UTC, tralkan commented
Hi @DevPH-Wistkey, let's move the src/lib files from the SSI Browser to tyron.js as well (and migrate to TypeScript). We have to remote "@zilliqa-js/zilliqa" & "arweave" from the SSI Browser.

2022-06-20 08:09 UTC, DevPH-Wistkey commented
Updated @tralkan

2022-06-21 02:48 UTC, tralkan requested changes

2022-06-21 02:48 UTC, txalkan commented on lib/blockchain/wallet.ts
> +import * as zcrypto from "@zilliqa-js/zilliqa"
import * as zcrypto from "@zilliqa-js/crypto"

2022-06-21 02:48 UTC, tralkan commented on lib/blockchain/wallet.ts
> +import * as zcrypto from '@zilliqa-js/zilliqa'
zilliqa-js/crypto

2022-06-21 02:48 UTC, tralkan commented on lib/blockchain/util.ts
> +    public static async AddLiquidity(
move AddLiquidity to /blockchain/defi-didDomain.ts

2022-06-21 02:48 UTC, tralkan commented on lib/blockchain/util.ts
> +    public static async RemoveLiquidity(
move RemoveLiquidity to blockchain/defi-didDomain.ts

2022-06-21 09:54 UTC, DevPH-Wistkey commented on lib/blockchain/wallet.ts
> +import * as zcrypto from '@zilliqa-js/zilliqa'
done @tralkan

2022-06-21 09:54 UTC, devwistkey commented on lib/blockchain/util.ts
> +    public static async AddLiquidity(
done @tralkan

2022-06-21 09:54 UTC, devwistkey commented on lib/blockchain/util.ts
> +    public static async RemoveLiquidity(
done @tralkan

2022-06-21 23:09 UTC, merged